package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * DrugTarget generated by hbm2java
 */
public class DrugTarget implements java.io.Serializable {

	private Integer drugTargetId;
	private int id;
	private String name;
	private String geneName;
	private int entrezGeneId;
	private String proteinId;
	private String geneId;
	private String uniprotId;
	private String uniprotTitle;
	private String pdbId;
	private String genecardId;
	private String genatlasId;
	private String hgncId;
	private String hprdId;
	private String speciesCategory;
	private String species;
	private String drugIds;

	public DrugTarget() {
	}

	public DrugTarget(int id, String name, String geneName, int entrezGeneId,
			String proteinId, String geneId, String uniprotId,
			String uniprotTitle, String pdbId, String genecardId,
			String genatlasId, String hgncId, String hprdId,
			String speciesCategory, String species, String drugIds) {
		this.id = id;
		this.name = name;
		this.geneName = geneName;
		this.entrezGeneId = entrezGeneId;
		this.proteinId = proteinId;
		this.geneId = geneId;
		this.uniprotId = uniprotId;
		this.uniprotTitle = uniprotTitle;
		this.pdbId = pdbId;
		this.genecardId = genecardId;
		this.genatlasId = genatlasId;
		this.hgncId = hgncId;
		this.hprdId = hprdId;
		this.speciesCategory = speciesCategory;
		this.species = species;
		this.drugIds = drugIds;
	}

	public Integer getDrugTargetId() {
		return this.drugTargetId;
	}

	public void setDrugTargetId(Integer drugTargetId) {
		this.drugTargetId = drugTargetId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGeneName() {
		return this.geneName;
	}

	public void setGeneName(String geneName) {
		this.geneName = geneName;
	}

	public int getEntrezGeneId() {
		return this.entrezGeneId;
	}

	public void setEntrezGeneId(int entrezGeneId) {
		this.entrezGeneId = entrezGeneId;
	}

	public String getProteinId() {
		return this.proteinId;
	}

	public void setProteinId(String proteinId) {
		this.proteinId = proteinId;
	}

	public String getGeneId() {
		return this.geneId;
	}

	public void setGeneId(String geneId) {
		this.geneId = geneId;
	}

	public String getUniprotId() {
		return this.uniprotId;
	}

	public void setUniprotId(String uniprotId) {
		this.uniprotId = uniprotId;
	}

	public String getUniprotTitle() {
		return this.uniprotTitle;
	}

	public void setUniprotTitle(String uniprotTitle) {
		this.uniprotTitle = uniprotTitle;
	}

	public String getPdbId() {
		return this.pdbId;
	}

	public void setPdbId(String pdbId) {
		this.pdbId = pdbId;
	}

	public String getGenecardId() {
		return this.genecardId;
	}

	public void setGenecardId(String genecardId) {
		this.genecardId = genecardId;
	}

	public String getGenatlasId() {
		return this.genatlasId;
	}

	public void setGenatlasId(String genatlasId) {
		this.genatlasId = genatlasId;
	}

	public String getHgncId() {
		return this.hgncId;
	}

	public void setHgncId(String hgncId) {
		this.hgncId = hgncId;
	}

	public String getHprdId() {
		return this.hprdId;
	}

	public void setHprdId(String hprdId) {
		this.hprdId = hprdId;
	}

	public String getSpeciesCategory() {
		return this.speciesCategory;
	}

	public void setSpeciesCategory(String speciesCategory) {
		this.speciesCategory = speciesCategory;
	}

	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	public String getDrugIds() {
		return this.drugIds;
	}

	public void setDrugIds(String drugIds) {
		this.drugIds = drugIds;
	}

}
