package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * Ensembl generated by hbm2java
 */
public class Ensembl implements java.io.Serializable {

	private Integer ensemblId;
	private String ensemblGeneId;
	private String ensemblTranscriptId;
	private String ensemblProteinId;
	private int geneId;

	public Ensembl() {
	}

	public Ensembl(String ensemblGeneId, String ensemblTranscriptId,
			String ensemblProteinId, int geneId) {
		this.ensemblGeneId = ensemblGeneId;
		this.ensemblTranscriptId = ensemblTranscriptId;
		this.ensemblProteinId = ensemblProteinId;
		this.geneId = geneId;
	}

	public Integer getEnsemblId() {
		return this.ensemblId;
	}

	public void setEnsemblId(Integer ensemblId) {
		this.ensemblId = ensemblId;
	}

	public String getEnsemblGeneId() {
		return this.ensemblGeneId;
	}

	public void setEnsemblGeneId(String ensemblGeneId) {
		this.ensemblGeneId = ensemblGeneId;
	}

	public String getEnsemblTranscriptId() {
		return this.ensemblTranscriptId;
	}

	public void setEnsemblTranscriptId(String ensemblTranscriptId) {
		this.ensemblTranscriptId = ensemblTranscriptId;
	}

	public String getEnsemblProteinId() {
		return this.ensemblProteinId;
	}

	public void setEnsemblProteinId(String ensemblProteinId) {
		this.ensemblProteinId = ensemblProteinId;
	}

	public int getGeneId() {
		return this.geneId;
	}

	public void setGeneId(int geneId) {
		this.geneId = geneId;
	}

}
