package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * Go generated by hbm2java
 */
public class Go implements java.io.Serializable {

	private Integer goId;
	private String id;
	private String name;
	private String nameSpace;
	private String description;

	public Go() {
	}

	public Go(String id, String name, String nameSpace, String description) {
		this.id = id;
		this.name = name;
		this.nameSpace = nameSpace;
		this.description = description;
	}

	public Integer getGoId() {
		return this.goId;
	}

	public void setGoId(Integer goId) {
		this.goId = goId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameSpace() {
		return this.nameSpace;
	}

	public void setNameSpace(String nameSpace) {
		this.nameSpace = nameSpace;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
