package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * HmddAllRaw generated by hbm2java
 */
public class HmddAllRaw implements java.io.Serializable {

	private Integer hmddAllId;
	private String mirnaRaw;
	private String mirna;
	private String disease;
	private int pubmed;
	private String description;

	public HmddAllRaw() {
	}

	public HmddAllRaw(String mirnaRaw, String mirna, String disease,
			int pubmed, String description) {
		this.mirnaRaw = mirnaRaw;
		this.mirna = mirna;
		this.disease = disease;
		this.pubmed = pubmed;
		this.description = description;
	}

	public Integer getHmddAllId() {
		return this.hmddAllId;
	}

	public void setHmddAllId(Integer hmddAllId) {
		this.hmddAllId = hmddAllId;
	}

	public String getMirnaRaw() {
		return this.mirnaRaw;
	}

	public void setMirnaRaw(String mirnaRaw) {
		this.mirnaRaw = mirnaRaw;
	}

	public String getMirna() {
		return this.mirna;
	}

	public void setMirna(String mirna) {
		this.mirna = mirna;
	}

	public String getDisease() {
		return this.disease;
	}

	public void setDisease(String disease) {
		this.disease = disease;
	}

	public int getPubmed() {
		return this.pubmed;
	}

	public void setPubmed(int pubmed) {
		this.pubmed = pubmed;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
