package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * MicroRnaOrg generated by hbm2java
 */
public class MicroRnaOrg implements java.io.Serializable {

	private MicroRnaOrgId id;
	private String mirbaseAcc;
	private String geneSymbol;
	private String transcriptId;
	private String extTranscriptId;
	private String mirnaAlignment;
	private String alignment;
	private String geneAlignment;
	private String mirnaStart;
	private String mirnaEnd;
	private int geneStart;
	private int geneEnd;
	private String genomeCoordinates;
	private float conservation;
	private float alignScore;
	private String seedCat;
	private String energy;
	private String mirsvrScore;

	public MicroRnaOrg() {
	}

	public MicroRnaOrg(MicroRnaOrgId id, String mirbaseAcc, String geneSymbol,
			String transcriptId, String extTranscriptId, String mirnaAlignment,
			String alignment, String geneAlignment, String mirnaStart,
			String mirnaEnd, int geneStart, int geneEnd,
			String genomeCoordinates, float conservation, float alignScore,
			String seedCat, String energy, String mirsvrScore) {
		this.id = id;
		this.mirbaseAcc = mirbaseAcc;
		this.geneSymbol = geneSymbol;
		this.transcriptId = transcriptId;
		this.extTranscriptId = extTranscriptId;
		this.mirnaAlignment = mirnaAlignment;
		this.alignment = alignment;
		this.geneAlignment = geneAlignment;
		this.mirnaStart = mirnaStart;
		this.mirnaEnd = mirnaEnd;
		this.geneStart = geneStart;
		this.geneEnd = geneEnd;
		this.genomeCoordinates = genomeCoordinates;
		this.conservation = conservation;
		this.alignScore = alignScore;
		this.seedCat = seedCat;
		this.energy = energy;
		this.mirsvrScore = mirsvrScore;
	}

	public MicroRnaOrgId getId() {
		return this.id;
	}

	public void setId(MicroRnaOrgId id) {
		this.id = id;
	}

	public String getMirbaseAcc() {
		return this.mirbaseAcc;
	}

	public void setMirbaseAcc(String mirbaseAcc) {
		this.mirbaseAcc = mirbaseAcc;
	}

	public String getGeneSymbol() {
		return this.geneSymbol;
	}

	public void setGeneSymbol(String geneSymbol) {
		this.geneSymbol = geneSymbol;
	}

	public String getTranscriptId() {
		return this.transcriptId;
	}

	public void setTranscriptId(String transcriptId) {
		this.transcriptId = transcriptId;
	}

	public String getExtTranscriptId() {
		return this.extTranscriptId;
	}

	public void setExtTranscriptId(String extTranscriptId) {
		this.extTranscriptId = extTranscriptId;
	}

	public String getMirnaAlignment() {
		return this.mirnaAlignment;
	}

	public void setMirnaAlignment(String mirnaAlignment) {
		this.mirnaAlignment = mirnaAlignment;
	}

	public String getAlignment() {
		return this.alignment;
	}

	public void setAlignment(String alignment) {
		this.alignment = alignment;
	}

	public String getGeneAlignment() {
		return this.geneAlignment;
	}

	public void setGeneAlignment(String geneAlignment) {
		this.geneAlignment = geneAlignment;
	}

	public String getMirnaStart() {
		return this.mirnaStart;
	}

	public void setMirnaStart(String mirnaStart) {
		this.mirnaStart = mirnaStart;
	}

	public String getMirnaEnd() {
		return this.mirnaEnd;
	}

	public void setMirnaEnd(String mirnaEnd) {
		this.mirnaEnd = mirnaEnd;
	}

	public int getGeneStart() {
		return this.geneStart;
	}

	public void setGeneStart(int geneStart) {
		this.geneStart = geneStart;
	}

	public int getGeneEnd() {
		return this.geneEnd;
	}

	public void setGeneEnd(int geneEnd) {
		this.geneEnd = geneEnd;
	}

	public String getGenomeCoordinates() {
		return this.genomeCoordinates;
	}

	public void setGenomeCoordinates(String genomeCoordinates) {
		this.genomeCoordinates = genomeCoordinates;
	}

	public float getConservation() {
		return this.conservation;
	}

	public void setConservation(float conservation) {
		this.conservation = conservation;
	}

	public float getAlignScore() {
		return this.alignScore;
	}

	public void setAlignScore(float alignScore) {
		this.alignScore = alignScore;
	}

	public String getSeedCat() {
		return this.seedCat;
	}

	public void setSeedCat(String seedCat) {
		this.seedCat = seedCat;
	}

	public String getEnergy() {
		return this.energy;
	}

	public void setEnergy(String energy) {
		this.energy = energy;
	}

	public String getMirsvrScore() {
		return this.mirsvrScore;
	}

	public void setMirsvrScore(String mirsvrScore) {
		this.mirsvrScore = mirsvrScore;
	}

}
