package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * MirnaMapId generated by hbm2java
 */
public class MirnaMapId implements java.io.Serializable {

	private int mirnaMapId;
	private String matureMirna;

	public MirnaMapId() {
	}

	public MirnaMapId(int mirnaMapId, String matureMirna) {
		this.mirnaMapId = mirnaMapId;
		this.matureMirna = matureMirna;
	}

	public int getMirnaMapId() {
		return this.mirnaMapId;
	}

	public void setMirnaMapId(int mirnaMapId) {
		this.mirnaMapId = mirnaMapId;
	}

	public String getMatureMirna() {
		return this.matureMirna;
	}

	public void setMatureMirna(String matureMirna) {
		this.matureMirna = matureMirna;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MirnaMapId))
			return false;
		MirnaMapId castOther = (MirnaMapId) other;

		return (this.getMirnaMapId() == castOther.getMirnaMapId())
				&& ((this.getMatureMirna() == castOther.getMatureMirna()) || (this
						.getMatureMirna() != null
						&& castOther.getMatureMirna() != null && this
						.getMatureMirna().equals(castOther.getMatureMirna())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMirnaMapId();
		result = 37
				* result
				+ (getMatureMirna() == null ? 0 : this.getMatureMirna()
						.hashCode());
		return result;
	}

}
