package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * Omim generated by hbm2java
 */
public class Omim implements java.io.Serializable {

	private Integer omimId;
	private String number;
	private String month;
	private String day;
	private String year;
	private String location;
	private String symbol;
	private String geneId;
	private String status;
	private String title;
	private String titleCont;
	private String mimNumber;
	private String method;
	private String comments;
	private String commentsCont;
	private String disorders;
	private String disordersCount1;
	private String disordersCount2;
	private String mouseCorrelate;
	private String reference;

	public Omim() {
	}

	public Omim(String number, String month, String day, String year,
			String location, String symbol, String geneId, String status,
			String title, String titleCont, String mimNumber, String method,
			String comments, String commentsCont, String disorders,
			String disordersCount1, String disordersCount2,
			String mouseCorrelate, String reference) {
		this.number = number;
		this.month = month;
		this.day = day;
		this.year = year;
		this.location = location;
		this.symbol = symbol;
		this.geneId = geneId;
		this.status = status;
		this.title = title;
		this.titleCont = titleCont;
		this.mimNumber = mimNumber;
		this.method = method;
		this.comments = comments;
		this.commentsCont = commentsCont;
		this.disorders = disorders;
		this.disordersCount1 = disordersCount1;
		this.disordersCount2 = disordersCount2;
		this.mouseCorrelate = mouseCorrelate;
		this.reference = reference;
	}

	public Integer getOmimId() {
		return this.omimId;
	}

	public void setOmimId(Integer omimId) {
		this.omimId = omimId;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public String getGeneId() {
		return this.geneId;
	}

	public void setGeneId(String geneId) {
		this.geneId = geneId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitleCont() {
		return this.titleCont;
	}

	public void setTitleCont(String titleCont) {
		this.titleCont = titleCont;
	}

	public String getMimNumber() {
		return this.mimNumber;
	}

	public void setMimNumber(String mimNumber) {
		this.mimNumber = mimNumber;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getCommentsCont() {
		return this.commentsCont;
	}

	public void setCommentsCont(String commentsCont) {
		this.commentsCont = commentsCont;
	}

	public String getDisorders() {
		return this.disorders;
	}

	public void setDisorders(String disorders) {
		this.disorders = disorders;
	}

	public String getDisordersCount1() {
		return this.disordersCount1;
	}

	public void setDisordersCount1(String disordersCount1) {
		this.disordersCount1 = disordersCount1;
	}

	public String getDisordersCount2() {
		return this.disordersCount2;
	}

	public void setDisordersCount2(String disordersCount2) {
		this.disordersCount2 = disordersCount2;
	}

	public String getMouseCorrelate() {
		return this.mouseCorrelate;
	}

	public void setMouseCorrelate(String mouseCorrelate) {
		this.mouseCorrelate = mouseCorrelate;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

}
