package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * Ppi2014 generated by hbm2java
 */
public class Ppi2014 implements java.io.Serializable {

	private Integer ppi2014Id;
	private int geneIdA;
	private int geneIdB;
	private String pubmed;
	private String database;

	public Ppi2014() {
	}

	public Ppi2014(int geneIdA, int geneIdB, String pubmed, String database) {
		this.geneIdA = geneIdA;
		this.geneIdB = geneIdB;
		this.pubmed = pubmed;
		this.database = database;
	}

	public Integer getPpi2014Id() {
		return this.ppi2014Id;
	}

	public void setPpi2014Id(Integer ppi2014Id) {
		this.ppi2014Id = ppi2014Id;
	}

	public int getGeneIdA() {
		return this.geneIdA;
	}

	public void setGeneIdA(int geneIdA) {
		this.geneIdA = geneIdA;
	}

	public int getGeneIdB() {
		return this.geneIdB;
	}

	public void setGeneIdB(int geneIdB) {
		this.geneIdB = geneIdB;
	}

	public String getPubmed() {
		return this.pubmed;
	}

	public void setPubmed(String pubmed) {
		this.pubmed = pubmed;
	}

	public String getDatabase() {
		return this.database;
	}

	public void setDatabase(String database) {
		this.database = database;
	}

}
