package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * PpiBindRaw generated by hbm2java
 */
public class PpiBindRaw implements java.io.Serializable {

	private Integer ppiBindRawId;
	private int bindId;
	private String molNameA;
	private String molTypeA;
	private int giA;
	private int geneA;
	private String taxA;
	private String molNameB;
	private String molTypeB;
	private int giB;
	private int geneB;
	private String taxB;
	private String pmid;

	public PpiBindRaw() {
	}

	public PpiBindRaw(int bindId, String molNameA, String molTypeA, int giA,
			int geneA, String taxA, String molNameB, String molTypeB, int giB,
			int geneB, String taxB, String pmid) {
		this.bindId = bindId;
		this.molNameA = molNameA;
		this.molTypeA = molTypeA;
		this.giA = giA;
		this.geneA = geneA;
		this.taxA = taxA;
		this.molNameB = molNameB;
		this.molTypeB = molTypeB;
		this.giB = giB;
		this.geneB = geneB;
		this.taxB = taxB;
		this.pmid = pmid;
	}

	public Integer getPpiBindRawId() {
		return this.ppiBindRawId;
	}

	public void setPpiBindRawId(Integer ppiBindRawId) {
		this.ppiBindRawId = ppiBindRawId;
	}

	public int getBindId() {
		return this.bindId;
	}

	public void setBindId(int bindId) {
		this.bindId = bindId;
	}

	public String getMolNameA() {
		return this.molNameA;
	}

	public void setMolNameA(String molNameA) {
		this.molNameA = molNameA;
	}

	public String getMolTypeA() {
		return this.molTypeA;
	}

	public void setMolTypeA(String molTypeA) {
		this.molTypeA = molTypeA;
	}

	public int getGiA() {
		return this.giA;
	}

	public void setGiA(int giA) {
		this.giA = giA;
	}

	public int getGeneA() {
		return this.geneA;
	}

	public void setGeneA(int geneA) {
		this.geneA = geneA;
	}

	public String getTaxA() {
		return this.taxA;
	}

	public void setTaxA(String taxA) {
		this.taxA = taxA;
	}

	public String getMolNameB() {
		return this.molNameB;
	}

	public void setMolNameB(String molNameB) {
		this.molNameB = molNameB;
	}

	public String getMolTypeB() {
		return this.molTypeB;
	}

	public void setMolTypeB(String molTypeB) {
		this.molTypeB = molTypeB;
	}

	public int getGiB() {
		return this.giB;
	}

	public void setGiB(int giB) {
		this.giB = giB;
	}

	public int getGeneB() {
		return this.geneB;
	}

	public void setGeneB(int geneB) {
		this.geneB = geneB;
	}

	public String getTaxB() {
		return this.taxB;
	}

	public void setTaxB(String taxB) {
		this.taxB = taxB;
	}

	public String getPmid() {
		return this.pmid;
	}

	public void setPmid(String pmid) {
		this.pmid = pmid;
	}

}
