package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * PpiDipRaw generated by hbm2java
 */
public class PpiDipRaw implements java.io.Serializable {

	private Integer autoid;
	private String idA;
	private String idB;
	private int geneIdA;
	private int geneIdB;
	private String altA;
	private String altB;
	private String aliasA;
	private String aliasB;
	private String method;
	private String author;
	private String publication;
	private String taxidA;
	private String taxidB;
	private String interactionType;
	private String database;
	private int identifier;
	private String confidence;
	private String status;

	public PpiDipRaw() {
	}

	public PpiDipRaw(String idA, String idB, int geneIdA, int geneIdB,
			String altA, String altB, String aliasA, String aliasB,
			String method, String author, String publication, String taxidA,
			String taxidB, String interactionType, String database,
			int identifier, String confidence, String status) {
		this.idA = idA;
		this.idB = idB;
		this.geneIdA = geneIdA;
		this.geneIdB = geneIdB;
		this.altA = altA;
		this.altB = altB;
		this.aliasA = aliasA;
		this.aliasB = aliasB;
		this.method = method;
		this.author = author;
		this.publication = publication;
		this.taxidA = taxidA;
		this.taxidB = taxidB;
		this.interactionType = interactionType;
		this.database = database;
		this.identifier = identifier;
		this.confidence = confidence;
		this.status = status;
	}

	public Integer getAutoid() {
		return this.autoid;
	}

	public void setAutoid(Integer autoid) {
		this.autoid = autoid;
	}

	public String getIdA() {
		return this.idA;
	}

	public void setIdA(String idA) {
		this.idA = idA;
	}

	public String getIdB() {
		return this.idB;
	}

	public void setIdB(String idB) {
		this.idB = idB;
	}

	public int getGeneIdA() {
		return this.geneIdA;
	}

	public void setGeneIdA(int geneIdA) {
		this.geneIdA = geneIdA;
	}

	public int getGeneIdB() {
		return this.geneIdB;
	}

	public void setGeneIdB(int geneIdB) {
		this.geneIdB = geneIdB;
	}

	public String getAltA() {
		return this.altA;
	}

	public void setAltA(String altA) {
		this.altA = altA;
	}

	public String getAltB() {
		return this.altB;
	}

	public void setAltB(String altB) {
		this.altB = altB;
	}

	public String getAliasA() {
		return this.aliasA;
	}

	public void setAliasA(String aliasA) {
		this.aliasA = aliasA;
	}

	public String getAliasB() {
		return this.aliasB;
	}

	public void setAliasB(String aliasB) {
		this.aliasB = aliasB;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getPublication() {
		return this.publication;
	}

	public void setPublication(String publication) {
		this.publication = publication;
	}

	public String getTaxidA() {
		return this.taxidA;
	}

	public void setTaxidA(String taxidA) {
		this.taxidA = taxidA;
	}

	public String getTaxidB() {
		return this.taxidB;
	}

	public void setTaxidB(String taxidB) {
		this.taxidB = taxidB;
	}

	public String getInteractionType() {
		return this.interactionType;
	}

	public void setInteractionType(String interactionType) {
		this.interactionType = interactionType;
	}

	public String getDatabase() {
		return this.database;
	}

	public void setDatabase(String database) {
		this.database = database;
	}

	public int getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(int identifier) {
		this.identifier = identifier;
	}

	public String getConfidence() {
		return this.confidence;
	}

	public void setConfidence(String confidence) {
		this.confidence = confidence;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
