package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * PpiIntact generated by hbm2java
 */
public class PpiIntact implements java.io.Serializable {

	private Integer ppiIntactId;
	private int geneIdA;
	private int geneIdB;
	private String pubmed;

	public PpiIntact() {
	}

	public PpiIntact(int geneIdA, int geneIdB, String pubmed) {
		this.geneIdA = geneIdA;
		this.geneIdB = geneIdB;
		this.pubmed = pubmed;
	}

	public Integer getPpiIntactId() {
		return this.ppiIntactId;
	}

	public void setPpiIntactId(Integer ppiIntactId) {
		this.ppiIntactId = ppiIntactId;
	}

	public int getGeneIdA() {
		return this.geneIdA;
	}

	public void setGeneIdA(int geneIdA) {
		this.geneIdA = geneIdA;
	}

	public int getGeneIdB() {
		return this.geneIdB;
	}

	public void setGeneIdB(int geneIdB) {
		this.geneIdB = geneIdB;
	}

	public String getPubmed() {
		return this.pubmed;
	}

	public void setPubmed(String pubmed) {
		this.pubmed = pubmed;
	}

}
