package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * Sirna generated by hbm2java
 */
public class Sirna implements java.io.Serializable {

	private Integer sirnaId;
	private int siRecords;
	private String pubMed;
	private String geneAc;
	private int geneId;
	private String symbol;
	private String db;
	private String siRnaSeq;
	private String siRnaLen;
	private String tissue;
	private String species;
	private String speciesScientific;
	private String method;
	private String testObject;
	private String testMethod;
	private String efficacyRating;

	public Sirna() {
	}

	public Sirna(int siRecords, String pubMed, String geneAc, int geneId,
			String symbol, String db, String siRnaSeq, String siRnaLen,
			String tissue, String species, String speciesScientific,
			String method, String testObject, String testMethod,
			String efficacyRating) {
		this.siRecords = siRecords;
		this.pubMed = pubMed;
		this.geneAc = geneAc;
		this.geneId = geneId;
		this.symbol = symbol;
		this.db = db;
		this.siRnaSeq = siRnaSeq;
		this.siRnaLen = siRnaLen;
		this.tissue = tissue;
		this.species = species;
		this.speciesScientific = speciesScientific;
		this.method = method;
		this.testObject = testObject;
		this.testMethod = testMethod;
		this.efficacyRating = efficacyRating;
	}

	public Integer getSirnaId() {
		return this.sirnaId;
	}

	public void setSirnaId(Integer sirnaId) {
		this.sirnaId = sirnaId;
	}

	public int getSiRecords() {
		return this.siRecords;
	}

	public void setSiRecords(int siRecords) {
		this.siRecords = siRecords;
	}

	public String getPubMed() {
		return this.pubMed;
	}

	public void setPubMed(String pubMed) {
		this.pubMed = pubMed;
	}

	public String getGeneAc() {
		return this.geneAc;
	}

	public void setGeneAc(String geneAc) {
		this.geneAc = geneAc;
	}

	public int getGeneId() {
		return this.geneId;
	}

	public void setGeneId(int geneId) {
		this.geneId = geneId;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public String getDb() {
		return this.db;
	}

	public void setDb(String db) {
		this.db = db;
	}

	public String getSiRnaSeq() {
		return this.siRnaSeq;
	}

	public void setSiRnaSeq(String siRnaSeq) {
		this.siRnaSeq = siRnaSeq;
	}

	public String getSiRnaLen() {
		return this.siRnaLen;
	}

	public void setSiRnaLen(String siRnaLen) {
		this.siRnaLen = siRnaLen;
	}

	public String getTissue() {
		return this.tissue;
	}

	public void setTissue(String tissue) {
		this.tissue = tissue;
	}

	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	public String getSpeciesScientific() {
		return this.speciesScientific;
	}

	public void setSpeciesScientific(String speciesScientific) {
		this.speciesScientific = speciesScientific;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public String getTestObject() {
		return this.testObject;
	}

	public void setTestObject(String testObject) {
		this.testObject = testObject;
	}

	public String getTestMethod() {
		return this.testMethod;
	}

	public void setTestMethod(String testMethod) {
		this.testMethod = testMethod;
	}

	public String getEfficacyRating() {
		return this.efficacyRating;
	}

	public void setEfficacyRating(String efficacyRating) {
		this.efficacyRating = efficacyRating;
	}

}
