package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * SubpathwayTargene generated by hbm2java
 */
public class SubpathwayTargene implements java.io.Serializable {

	private Integer subpathwayId;
	private int targetGene;

	public SubpathwayTargene() {
	}

	public SubpathwayTargene(int targetGene) {
		this.targetGene = targetGene;
	}

	public Integer getSubpathwayId() {
		return this.subpathwayId;
	}

	public void setSubpathwayId(Integer subpathwayId) {
		this.subpathwayId = subpathwayId;
	}

	public int getTargetGene() {
		return this.targetGene;
	}

	public void setTargetGene(int targetGene) {
		this.targetGene = targetGene;
	}

}
