package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * SubpathwayPure generated by hbm2java
 */
public class SubpathwayPure implements java.io.Serializable {

	private Integer subpathwayId;
	private int targetGene;
	private int geneLevel1;
	private int geneLevel2;
	private double bpJaccardCoefficient;
	private double mcJaccardCoefficient;

	public SubpathwayPure() {
	}

	public SubpathwayPure(int targetGene, int geneLevel1, int geneLevel2,
			double bpJaccardCoefficient, double mcJaccardCoefficient) {
		this.targetGene = targetGene;
		this.geneLevel1 = geneLevel1;
		this.geneLevel2 = geneLevel2;
		this.bpJaccardCoefficient = bpJaccardCoefficient;
		this.mcJaccardCoefficient = mcJaccardCoefficient;
	}

	public Integer getSubpathwayId() {
		return this.subpathwayId;
	}

	public void setSubpathwayId(Integer subpathwayId) {
		this.subpathwayId = subpathwayId;
	}

	public int getTargetGene() {
		return this.targetGene;
	}

	public void setTargetGene(int targetGene) {
		this.targetGene = targetGene;
	}

	public int getGeneLevel1() {
		return this.geneLevel1;
	}

	public void setGeneLevel1(int geneLevel1) {
		this.geneLevel1 = geneLevel1;
	}

	public int getGeneLevel2() {
		return this.geneLevel2;
	}

	public void setGeneLevel2(int geneLevel2) {
		this.geneLevel2 = geneLevel2;
	}

	public double getBpJaccardCoefficient() {
		return this.bpJaccardCoefficient;
	}

	public void setBpJaccardCoefficient(double bpJaccardCoefficient) {
		this.bpJaccardCoefficient = bpJaccardCoefficient;
	}

	public double getMcJaccardCoefficient() {
		return this.mcJaccardCoefficient;
	}

	public void setMcJaccardCoefficient(double mcJaccardCoefficient) {
		this.mcJaccardCoefficient = mcJaccardCoefficient;
	}

}
