package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * SubpathwayService generated by hbm2java
 */
public class SubpathwayService implements java.io.Serializable {

	private Integer subpathwayId;
	private int targetGene;
	private String symbolTarget;
	private int tfTarget;
	private int rcTarget;
	private String roleTarget;
	private String omimTarget;
	private String tissueTarget;
	private int geneLevel1;
	private String symbol1;
	private int tf1;
	private int rc1;
	private String role1;
	private String omim1;
	private String tissue1;
	private int geneLevel2;
	private String symbol2;
	private int tf2;
	private int rc2;
	private String role2;
	private String omim2;
	private String tissue2;
	private String kegg;
	private double bpJaccardCoefficient;
	private double mcJaccardCoefficient;

	public SubpathwayService() {
	}

	public SubpathwayService(int targetGene, String symbolTarget, int tfTarget, int rcTarget,
			String roleTarget, String omimTarget, String tissueTarget,
			int geneLevel1, String symbol1, int tf1, int rc1, String role1, String omim1,
			String tissue1, int geneLevel2, String symbol2, int tf2, int rc2, String role2,
			String omim2, String tissue2, String kegg,
			double bpJaccardCoefficient, double mcJaccardCoefficient) {
		this.targetGene = targetGene;
		this.symbolTarget = symbolTarget;
		this.tfTarget = tfTarget;
		this.rcTarget = rcTarget;
		this.roleTarget = roleTarget;
		this.omimTarget = omimTarget;
		this.tissueTarget = tissueTarget;
		this.geneLevel1 = geneLevel1;
		this.symbol1 = symbol1;
		this.tf1 = tf1;
		this.rc1 = rc1;
		this.role1 = role1;
		this.omim1 = omim1;
		this.tissue1 = tissue1;
		this.geneLevel2 = geneLevel2;
		this.symbol2 = symbol2;
		this.tf2 = tf2;
		this.rc2 = rc2;
		this.role2 = role2;
		this.omim2 = omim2;
		this.tissue2 = tissue2;
		this.kegg = kegg;
		this.bpJaccardCoefficient = bpJaccardCoefficient;
		this.mcJaccardCoefficient = mcJaccardCoefficient;
	}

	
	public int getTfTarget() {
		return tfTarget;
	}

	public void setTfTarget(int tfTarget) {
		this.tfTarget = tfTarget;
	}

	public int getRcTarget() {
		return rcTarget;
	}

	public void setRcTarget(int rcTarget) {
		this.rcTarget = rcTarget;
	}

	public int getTf1() {
		return tf1;
	}

	public void setTf1(int tf1) {
		this.tf1 = tf1;
	}

	public int getRc1() {
		return rc1;
	}

	public void setRc1(int rc1) {
		this.rc1 = rc1;
	}

	public int getTf2() {
		return tf2;
	}

	public void setTf2(int tf2) {
		this.tf2 = tf2;
	}

	public int getRc2() {
		return rc2;
	}

	public void setRc2(int rc2) {
		this.rc2 = rc2;
	}

	public Integer getSubpathwayId() {
		return this.subpathwayId;
	}

	public void setSubpathwayId(Integer subpathwayId) {
		this.subpathwayId = subpathwayId;
	}

	public int getTargetGene() {
		return this.targetGene;
	}

	public void setTargetGene(int targetGene) {
		this.targetGene = targetGene;
	}

	public String getSymbolTarget() {
		return this.symbolTarget;
	}

	public void setSymbolTarget(String symbolTarget) {
		this.symbolTarget = symbolTarget;
	}

	public String getRoleTarget() {
		return this.roleTarget;
	}

	public void setRoleTarget(String roleTarget) {
		this.roleTarget = roleTarget;
	}

	public String getOmimTarget() {
		return this.omimTarget;
	}

	public void setOmimTarget(String omimTarget) {
		this.omimTarget = omimTarget;
	}

	public String getTissueTarget() {
		return this.tissueTarget;
	}

	public void setTissueTarget(String tissueTarget) {
		this.tissueTarget = tissueTarget;
	}

	public int getGeneLevel1() {
		return this.geneLevel1;
	}

	public void setGeneLevel1(int geneLevel1) {
		this.geneLevel1 = geneLevel1;
	}

	public String getSymbol1() {
		return this.symbol1;
	}

	public void setSymbol1(String symbol1) {
		this.symbol1 = symbol1;
	}

	public String getRole1() {
		return this.role1;
	}

	public void setRole1(String role1) {
		this.role1 = role1;
	}

	public String getOmim1() {
		return this.omim1;
	}

	public void setOmim1(String omim1) {
		this.omim1 = omim1;
	}

	public String getTissue1() {
		return this.tissue1;
	}

	public void setTissue1(String tissue1) {
		this.tissue1 = tissue1;
	}

	public int getGeneLevel2() {
		return this.geneLevel2;
	}

	public void setGeneLevel2(int geneLevel2) {
		this.geneLevel2 = geneLevel2;
	}

	public String getSymbol2() {
		return this.symbol2;
	}

	public void setSymbol2(String symbol2) {
		this.symbol2 = symbol2;
	}

	public String getRole2() {
		return this.role2;
	}

	public void setRole2(String role2) {
		this.role2 = role2;
	}

	public String getOmim2() {
		return this.omim2;
	}

	public void setOmim2(String omim2) {
		this.omim2 = omim2;
	}

	public String getTissue2() {
		return this.tissue2;
	}

	public void setTissue2(String tissue2) {
		this.tissue2 = tissue2;
	}

	public String getKegg() {
		return this.kegg;
	}

	public void setKegg(String kegg) {
		this.kegg = kegg;
	}

	public double getBpJaccardCoefficient() {
		return this.bpJaccardCoefficient;
	}

	public void setBpJaccardCoefficient(double bpJaccardCoefficient) {
		this.bpJaccardCoefficient = bpJaccardCoefficient;
	}

	public double getMcJaccardCoefficient() {
		return this.mcJaccardCoefficient;
	}

	public void setMcJaccardCoefficient(double mcJaccardCoefficient) {
		this.mcJaccardCoefficient = mcJaccardCoefficient;
	}

}
