package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private Integer tagId;
	private String symbol;
	private int geneId;
	private String location;
	private String category;
	private String description;
	private String chromosome;

	public Tag() {
	}

	public Tag(String symbol, int geneId, String location, String category,
			String description, String chromosome) {
		this.symbol = symbol;
		this.geneId = geneId;
		this.location = location;
		this.category = category;
		this.description = description;
		this.chromosome = chromosome;
	}

	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public int getGeneId() {
		return this.geneId;
	}

	public void setGeneId(int geneId) {
		this.geneId = geneId;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getChromosome() {
		return this.chromosome;
	}

	public void setChromosome(String chromosome) {
		this.chromosome = chromosome;
	}

}
