package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * Unigene generated by hbm2java
 */
public class Unigene implements java.io.Serializable {

	private Integer unigeneId;
	private String id;
	private int geneId;
	private String express;

	public Unigene() {
	}

	public Unigene(String id, int geneId, String express) {
		this.id = id;
		this.geneId = geneId;
		this.express = express;
	}

	public Integer getUnigeneId() {
		return this.unigeneId;
	}

	public void setUnigeneId(Integer unigeneId) {
		this.unigeneId = unigeneId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getGeneId() {
		return this.geneId;
	}

	public void setGeneId(int geneId) {
		this.geneId = geneId;
	}

	public String getExpress() {
		return this.express;
	}

	public void setExpress(String express) {
		this.express = express;
	}

}
