package edu.map.ws.persistent.dao;

// Generated 2014/8/6 �W�� 10:27:37 by Hibernate Tools 3.4.0.CR1

/**
 * Uniprot generated by hbm2java
 */
public class Uniprot implements java.io.Serializable {

	private Integer uniprotId;
	private String uniprotkbAc;
	private String uniprotkbId;
	private int geneId;
	private String refseq;
	private String gi;
	private String pdb;
	private String go;
	private String ipi;
	private String uniref100;
	private String uniref90;
	private String uniref50;
	private String uniparc;
	private String pir;
	private int taxon;
	private String mim;
	private String unigene;
	private String pubmed;
	private String embl;
	private String emblCds;
	private String ensembl;
	private String ensemblTrs;
	private String ensemblPro;
	private String additionalPubmed;

	public Uniprot() {
	}

	public Uniprot(String uniprotkbAc, String uniprotkbId, int geneId,
			String refseq, String gi, String pdb, String go, String ipi,
			String uniref100, String uniref90, String uniref50, String uniparc,
			String pir, int taxon, String mim, String unigene, String pubmed,
			String embl, String emblCds, String ensembl, String ensemblTrs,
			String ensemblPro, String additionalPubmed) {
		this.uniprotkbAc = uniprotkbAc;
		this.uniprotkbId = uniprotkbId;
		this.geneId = geneId;
		this.refseq = refseq;
		this.gi = gi;
		this.pdb = pdb;
		this.go = go;
		this.ipi = ipi;
		this.uniref100 = uniref100;
		this.uniref90 = uniref90;
		this.uniref50 = uniref50;
		this.uniparc = uniparc;
		this.pir = pir;
		this.taxon = taxon;
		this.mim = mim;
		this.unigene = unigene;
		this.pubmed = pubmed;
		this.embl = embl;
		this.emblCds = emblCds;
		this.ensembl = ensembl;
		this.ensemblTrs = ensemblTrs;
		this.ensemblPro = ensemblPro;
		this.additionalPubmed = additionalPubmed;
	}

	public Integer getUniprotId() {
		return this.uniprotId;
	}

	public void setUniprotId(Integer uniprotId) {
		this.uniprotId = uniprotId;
	}

	public String getUniprotkbAc() {
		return this.uniprotkbAc;
	}

	public void setUniprotkbAc(String uniprotkbAc) {
		this.uniprotkbAc = uniprotkbAc;
	}

	public String getUniprotkbId() {
		return this.uniprotkbId;
	}

	public void setUniprotkbId(String uniprotkbId) {
		this.uniprotkbId = uniprotkbId;
	}

	public int getGeneId() {
		return this.geneId;
	}

	public void setGeneId(int geneId) {
		this.geneId = geneId;
	}

	public String getRefseq() {
		return this.refseq;
	}

	public void setRefseq(String refseq) {
		this.refseq = refseq;
	}

	public String getGi() {
		return this.gi;
	}

	public void setGi(String gi) {
		this.gi = gi;
	}

	public String getPdb() {
		return this.pdb;
	}

	public void setPdb(String pdb) {
		this.pdb = pdb;
	}

	public String getGo() {
		return this.go;
	}

	public void setGo(String go) {
		this.go = go;
	}

	public String getIpi() {
		return this.ipi;
	}

	public void setIpi(String ipi) {
		this.ipi = ipi;
	}

	public String getUniref100() {
		return this.uniref100;
	}

	public void setUniref100(String uniref100) {
		this.uniref100 = uniref100;
	}

	public String getUniref90() {
		return this.uniref90;
	}

	public void setUniref90(String uniref90) {
		this.uniref90 = uniref90;
	}

	public String getUniref50() {
		return this.uniref50;
	}

	public void setUniref50(String uniref50) {
		this.uniref50 = uniref50;
	}

	public String getUniparc() {
		return this.uniparc;
	}

	public void setUniparc(String uniparc) {
		this.uniparc = uniparc;
	}

	public String getPir() {
		return this.pir;
	}

	public void setPir(String pir) {
		this.pir = pir;
	}

	public int getTaxon() {
		return this.taxon;
	}

	public void setTaxon(int taxon) {
		this.taxon = taxon;
	}

	public String getMim() {
		return this.mim;
	}

	public void setMim(String mim) {
		this.mim = mim;
	}

	public String getUnigene() {
		return this.unigene;
	}

	public void setUnigene(String unigene) {
		this.unigene = unigene;
	}

	public String getPubmed() {
		return this.pubmed;
	}

	public void setPubmed(String pubmed) {
		this.pubmed = pubmed;
	}

	public String getEmbl() {
		return this.embl;
	}

	public void setEmbl(String embl) {
		this.embl = embl;
	}

	public String getEmblCds() {
		return this.emblCds;
	}

	public void setEmblCds(String emblCds) {
		this.emblCds = emblCds;
	}

	public String getEnsembl() {
		return this.ensembl;
	}

	public void setEnsembl(String ensembl) {
		this.ensembl = ensembl;
	}

	public String getEnsemblTrs() {
		return this.ensemblTrs;
	}

	public void setEnsemblTrs(String ensemblTrs) {
		this.ensemblTrs = ensemblTrs;
	}

	public String getEnsemblPro() {
		return this.ensemblPro;
	}

	public void setEnsemblPro(String ensemblPro) {
		this.ensemblPro = ensemblPro;
	}

	public String getAdditionalPubmed() {
		return this.additionalPubmed;
	}

	public void setAdditionalPubmed(String additionalPubmed) {
		this.additionalPubmed = additionalPubmed;
	}

}
